Repository ynput/ayon-premiere, pull requests merged in 2025-03, with the labels that each got.

#16 Fix: container bins are pushed back to root during update
  client/ayon_premiere/api/extension.zxp
  client/ayon_premiere/api/extension/CSXS/manifest.xml
  client/ayon_premiere/api/extension/js/main.js
  client/ayon_premiere/api/extension/jsx/hostscript.jsx
Labels: bug, sponsored

#17 Enhancement: implement version changes in scene inventory
  client/ayon_premiere/api/extension.zxp
  client/ayon_premiere/api/extension/CSXS/manifest.xml
  client/ayon_premiere/api/extension/js/main.js
  client/ayon_premiere/api/extension/jsx/hostscript.jsx
  client/ayon_premiere/api/pipeline.py
  client/ayon_premiere/api/ws_stub.py
  client/ayon_premiere/plugins/load/load_aftereffects_comp.py
Labels: enhancement, sponsored

#19 Automated mkdocs setup
  .gitignore
  docs/css/custom.css
  docs/img/ay-symbol-blackw-full.png
  docs/img/favicon.ico
  docs/index.md
  docs/license.md
  mkdocs.yml
  mkdocs_hooks.py
  pyproject.toml
  uv.lock
Labels: type: feature

#20 Fix loaded items are not showing in deeper levels
  client/ayon_premiere/api/extension.zxp
  client/ayon_premiere/api/extension/CSXS/manifest.xml
  client/ayon_premiere/api/extension/jsx/hostscript.jsx
Labels: type: bug, sponsored
