Repository ynput/ayon-premiere, pull requests merged in 2025-01, with the labels that each got.

#7 Implemented Loader functionality
  README.md
  client/ayon_premiere/api/__init__.py
  client/ayon_premiere/api/extension.zxp
  client/ayon_premiere/api/extension/CSXS/manifest.xml
  client/ayon_premiere/api/extension/js/main.js
  client/ayon_premiere/api/extension/jsx/hostscript.jsx
  client/ayon_premiere/api/lib.py
  client/ayon_premiere/api/pipeline.py
  client/ayon_premiere/api/plugin.py
  client/ayon_premiere/api/ws_stub.py
  client/ayon_premiere/plugins/load/load_file.py
  client/ayon_premiere/version.py
  package.py
Labels: sponsored, type: feature

#8 Fix moving loaded bins into hierarchy
  client/ayon_premiere/api/extension.zxp
  client/ayon_premiere/api/extension/CSXS/manifest.xml
  client/ayon_premiere/api/extension/jsx/hostscript.jsx
Labels: bug

#9 Fix: container update affects other clips
  client/ayon_premiere/api/extension.zxp
  client/ayon_premiere/api/extension/CSXS/manifest.xml
  client/ayon_premiere/api/extension/jsx/hostscript.jsx
Labels: bug, sponsored

#6 pre launch hook for installing AYON extension
  client/ayon_premiere/api/extension.zxp
  client/ayon_premiere/api/extension/CSXS/manifest.xml
  client/ayon_premiere/hooks/pre_launch_install_ayon_extension.py
  server/__init__.py
  server/settings.py
Labels: enhancement
